### ISSUE TITLE
Not running on kali 

### ISSUE THREAD

**Issue by moreirapenna2** [savio-code/ghost-phisher#44]
Hello, so, i tried downloading via apt-get and through git-clone, when running both i get the following error: TypeError: 'errors' is an invalid keyword argument for this function.
I haven't found any solution on the internet so i posted it here, the full error is: 
Traceback (most recent call last):
  File "ghost.py", line 15, in <module>
    from gui import *
  File "/root/ghost-phisher/Ghost-Phisher/gui/ghost_phisher.py", line 19, in <module>
    from core.ghost_dns import *
  File "/root/ghost-phisher/Ghost-Phisher/core/ghost_dns.py", line 33, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
    f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function

Everything is updated (including Scapy), any solution?

**Comment by SecureCloud-biz** [comment]
no help i guess
