### ISSUE TITLE
Error when starting ghost-phisher.

### ISSUE THREAD

**Issue by retriple333** [savio-code/ghost-phisher#50]
root@kali:~# ghost-phisher
Traceback (most recent call last):
  File "ghost.py", line 15, in <module>
    from gui import *
  File "/usr/share/ghost-phisher/gui/ghost_phisher.py", line 19, in <module>
    from core.ghost_dns import *
  File "/usr/share/ghost-phisher/core/ghost_dns.py", line 33, in <module>
    from scapy.all import *
  File "/usr/lib/python2.7/dist-packages/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/usr/lib/python2.7/dist-packages/scapy/arch/__init__.py", line 20, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/usr/lib/python2.7/dist-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/usr/lib/python2.7/dist-packages/matplotlib/contour.py", line 21, in <module>
    import matplotlib.font_manager as font_manager
  File "/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py", line 1458, in <module>
    _rebuild()
  File "/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py", line 1438, in _rebuild
    fontManager = FontManager()
  File "/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py", line 1083, in __init__
    self.afmlist = createFontList(self.afmfiles, fontext='afm')
  File "/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py", line 570, in createFontList
    font = afm.AFM(fh)
  File "/usr/lib/python2.7/dist-packages/matplotlib/afm.py", line 337, in __init__
    parse_afm(fh)
  File "/usr/lib/python2.7/dist-packages/matplotlib/afm.py", line 326, in parse_afm
    doptional = _parse_optional(fh)
  File "/usr/lib/python2.7/dist-packages/matplotlib/afm.py", line 306, in _parse_optional
    d[key] = optional[key](fh)
  File "/usr/lib/python2.7/dist-packages/matplotlib/afm.py", line 235, in _parse_kern_pairs
    for line in fh:
IOError: [Errno 5] Input/output error

Looks to be a python error, but I'm truly not sure. 

Thanks in advance

**Comment by SecureCloud-biz** [comment]
same here
